### ISSUE TITLE
Cannot use eval_field() as described in README.md

### ISSUE THREAD

**Issue by vonopr** [ofershamir/matsuno#3]
Hello! 
Thank you for a useful test case and its open source supplement.

I cannot use function `eval_field()` in a way described in your `README.md`
After having installed your package with `pip install pymaws` I try
```python
from pymaws import *
eval_field()
```
and get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'eval_field' is not defined
```
As your `pymaws/__init__.py` does not import `eval_field()` I have no access to it at the moment.
The following works for me:
```python
from pymaws import pymaws
pymaws.eval_field
```
prints
```
<function eval_field at 0x7f1a8869d3a0>
```

Consider importing `eval_field()` by adding line  `from .pymaws import  eval_fields` into your `pymaws/__init__.py`. So, your example would work. Alternatively, you could change the example's description and do not modify the code.

**Comment by ofershamir** [comment]
Hi,

I have installed the package from scratch (new environment and cloned the repo directly from GitHub) and ran the example precisely as specified in README.md, and it works for me.

Did you get an `OK` on `python test_pymaws.py`?

Note that `eval_field()` without inputs should raise an error (a different one from what you got) because it expects inputs for lat, lon, time. Doing an `eval_field?` does recognize the function for me (the correct one belonging to the package).

**Comment by vonopr** [comment]
Yes, after downloading the repository and installing the package I go to `matsuno/pymaws` directory, run `python test_pymaws.py` and get OK.

After that I can successfully import `eval_field`. Executing
 ```python -c "from pymaws import *; v=eval_field(0.1, 0.0, 0.0, field='v'); print(v)"```
prints `5.963302895132373e-06`. 

But this works only because I am in the special directory `matsuno/pymaws` . The python interpreter can find pymaws module because there is `pymaws.py` file in the same directory. If I change the directory I get an error:
```cwd
cd ../..
python -c "from pymaws import *; v=eval_field(0.1, 0.0, 0.0, field='v'); print(v)"
```
results in
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'eval_field' is not defined
```
Installation of a python package either from PyPi or local installation  imply that I can use it with a proper python interpreter from any directory. If the code is supposed to be executed only in its own directory there is no need in the setup script. 

Adding 
```python
from .pymaws import eval_field
```
to the bottom of your `pymaws/__init__.py` and re-installing the package fixes the issue.
